# -*- coding: utf-8 -*-
"""Case in Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RSjjqRtHvdzIeJ2OU-4k-ye98b-dagpk

# **TUGAS PYTHON KELAS QA - ZAHROTUL AULIA**

# Conditions
"""

mapel = ['Bahasa Indonesia', 'Bahasa Inggris', 'Matematika', 'IPA']

nama = input("Masukkan nama siswa: ")
mtk = float(input("Masukkan Nilai Matematika: "))
ipa = float(input("Masukkan Nilai IPA: "))
bindo = float(input("Masukkan Nilai Bahasa Indonesia: "))
bing = float(input("Masukkan Nilai Bahasa Inggris: "))
rataan = (mtk + ipa + bindo + bing) / len(mapel)

if rataan < 75: 
  print("\nKami telah merekap hasil ujian dari", nama, "bahwa rata-rata nilai yang diperoleh sebesar", rataan, "maka Anda dinyatakan TIDAK LULUS")
elif rataan > 75: 
  print("\nKami telah merekap hasil ujian dari", nama, "bahwa rata-rata nilai yang diperoleh sebesar", rataan, "maka Anda dinyatakan LULUS")
else:
  print("\nKami telah merekap hasil ujian dari", nama, "bahwa rata-rata nilai yang diperoleh sebesar", rataan, "maka Anda bisa mengulang kembali")

"""# Looping - For"""

nama = ["Cindy", "Dei", "Sarah", "Aulia", "Akram", "Kevin", "Christopher", "Krissy"]

for n in nama:
  print("Hi, " + n + "! Jangan lupa hari ini ada kelas QA ya... See you!\n")

for a in range(1,11,1):
    if a % 2 == 0:
      print("Angka", a, "merupakan bilangan genap di antara bilangan 1 sampai 11")
    else:
      print("Angka", a, "merupakan bilangan ganjil di antara bilangan 1 sampai 11")

"""# Looping - While"""

y = 0
while y < 25:
  y += 1
  print(f"Berapakah hasil dua kali dari {y}?")
  y = y * 2
  print("Jawab: ", y)

"""# Function"""

p = float(input("Panjang Balok: "))
l = float(input("Lebar Balok: "))
t = float(input("Tinggi Balok: "))

print("\nSebuah balok diketahui panjang", p, "cm, lebar", l, "cm dan tinggi", t, "cm. Tentukan:")
print('''
a. Panjang kawat yang dibutuhkan
b. Luas permukaan balok
c. Volume balok
''')
print("Jawaban :")

def PanjangKawatBalok():
  PK = 4 * (p + l + t)
  print("a. Panjang kawat yang dibutuhkan adalah", PK, "cm.")

def LuasPermukaanBalok():
  LP = 2 * ((p * l) + (p * t) + (l * t))
  print("b. Luas permukaan balok adalah", LP, "cm^2.")

def VolumeBalok():
  V = p * l * t
  print("c. Volume balok adalah", V, "cm^3.")

PanjangKawatBalok()
LuasPermukaanBalok()
VolumeBalok()

"""# OOP (Object Oriented Programming)"""

class Taman:
  def __init__(taman, panjang, lebar):
    taman.panjang = panjang
    taman.lebar = lebar
  def function(self):
    print("Saya memiliki taman dengan panjang", self.panjang, "m dan lebar", self.lebar, "m.")
    luas = self.panjang * self.lebar
    print("Maka luas taman yang saya miliki adalah", luas, "m^2.\n")

#deklarasi object
cindy = Taman(3, 2)
sarah = Taman(4, 2)
dei = Taman(5, 2)

cindy.function()
sarah.function()
dei.function()